gesture_classification:
  device: cpu
  model_path: model/keypoint_classifier/checkpoint_8gestures.pt
  labels_path: model/keypoint_classifier/keypoint_classifier_6label.csv
  score_th: 0.5

mediapipe:
  use_static_image_mode: false
  max_num_hands: 1
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5

demo:
  cap_width: 1280
  cap_height: 720
  draw_bbox: true

